name: Nethermind JSON-RPC Tests

on: [push, pull_request]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce
          sudo usermod -aG docker $USER

      - name: Install Docker Compose
        run: |
          #sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          #sudo chmod +x /usr/local/bin/docker-compose
          # sudo apt-get install docker-compose-plugin
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          ls -la /usr/local/bin/
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Download Sedge
        run: |
          curl -L https://github.com/NethermindEth/sedge/releases/download/v1.3.2/sedge-v1.3.2-linux-amd64 --output sedge
          ls -l sedge  # List file details to check download

      - name: Set permissions for Sedge
        run: |
          chmod +x sedge
          ls -l sedge  # List file details to check permissions

      - name: Move Sedge to /usr/local/bin
        run: |
          sudo mv sedge /usr/local/bin/sedge
          sudo ln -s /usr/local/bin/sedge /usr/bin/sedge
          which sedge  # Verify the location of sedge
          sedge version  # Check if sedge is executable

      - name: Setup Sedge environment
        run: |
          sedge deps install >> sedge.logs
          sedge generate --logging none -p $HOME full-node \
          --map-all --no-mev-boost --no-validator \
          --network chiado -c lighthouse:sigp/lighthouse:latest \
          -e nethermind:nethermindeth/nethermind:master \
          --el-extra-flag Sync.NonValidatorNode=true \
          --el-extra-flag Sync.DownloadBodiesInFastSync=false \
          --el-extra-flag Sync.DownloadReceiptsInFastSync=false \
          --el-extra-flag JsonRpc.EnabledModules=[Eth,TxPool,Web3,Net,Health,Rpc,Debug] \
          --cl-extra-flag checkpoint-sync-url=http://139.144.26.89:4000/ >> sedge.logs

      - name: Run Sedge
        run: sedge run -p . >> sedge.logs &
        timeout-minutes: 5

      - name: Wait for Nethermind synchronization
        run: sleep 300

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run verification tests
        run: |
          pytest tests/test_json_rpc.py

      - name: Upload Sedge logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: sedge-logs
          path: sedge.logs